/* ============================================================
   GIESAC — Datos de proyectos (20 proyectos)
   Se reutilizan imágenes existentes como placeholder hasta
   disponer de fotografías reales por proyecto.
   ============================================================ */
'use strict';

window.PROYECTOS = [
  { id: 'parque-incario', nombre: 'Parque Incario — Armando Paredes', cliente: 'Morada', tipo: 'Vivienda Multifamiliar', ubicacion: 'San Miguel', anio: 2024, desc: 'Diseño de instalaciones y gestión BIM para un conjunto residencial multifamiliar.', fotos: ['images/recurso-1.png', 'images/recurso-3.png', 'images/recurso-bim-monitor.png'] },
  { id: 'bustamante-2', nombre: 'Bustamante 2', cliente: 'Morada', tipo: 'Vivienda Multifamiliar', ubicacion: 'Miraflores', anio: 2024, desc: 'Ingeniería multidisciplinaria y coordinación BIM para edificio multifamiliar.', fotos: ['images/recurso-2.png', 'images/recurso-4.png', 'images/recurso-1.png'] },
  { id: 'multifamiliar-san-miguel', nombre: 'Multifamiliar San Miguel', cliente: '—', tipo: 'Vivienda Multifamiliar', ubicacion: 'San Miguel', anio: 2023, desc: 'Proyecto residencial con ingeniería eléctrica, mecánica y sanitaria.', fotos: ['images/recurso-3.png', 'images/recurso-2.png'] },
  { id: 'torre-tale', nombre: 'Multifamiliar Torre Tale', cliente: 'Tale Inmobiliaria', tipo: 'Vivienda Multifamiliar', ubicacion: 'Surco', anio: 2023, desc: 'Instalaciones bajo metodología VDC/BIM y estudio de flujo dinámico computacional.', fotos: ['images/recurso-4.png', 'images/recurso-1.png', 'images/recurso-bim-monitor.png'] },
  { id: 'jorge-chavez', nombre: 'Aeropuerto Internacional Jorge Chávez', cliente: 'LAP', tipo: 'Infraestructura y Transporte', ubicacion: 'Callao', anio: 2022, desc: 'Estudio de flujo dinámico computacional (CFD) para confort térmico y eficiencia energética de la envolvente.', fotos: ['images/nuevo-jorge-chavez.jpg', 'images/recurso-bim-monitor.png', 'images/recurso-3.png'] },
  { id: 'instalaciones-corporativas', nombre: 'Instalaciones Corporativas', cliente: '—', tipo: 'Oficinas', ubicacion: 'San Isidro', anio: 2022, desc: 'Coordinación BIM de instalaciones para edificio corporativo.', fotos: ['images/recurso-1.png', 'images/recurso-2.png', 'images/recurso-bim-monitor.png'] },
  { id: 'cantabria', nombre: 'Centro Comercial Cantabria', cliente: 'Cantabria Inmobiliaria', tipo: 'Comercial', ubicacion: 'La Molina', anio: 2022, desc: 'Estructuras e ingeniería eléctrica, mecánica, sanitaria y contra incendio.', fotos: ['images/recurso-1.png', 'images/recurso-4.png'] },
  { id: 'estadio-nacional', nombre: 'Remodelación Estadio Nacional', cliente: 'IPD', tipo: 'Institucional', ubicacion: 'Cercado de Lima', anio: 2021, desc: 'Proyecto de referencia en la trayectoria de más de 13 años de la empresa.', fotos: ['images/recurso-2.png', 'images/recurso-5.jpg', 'images/recurso-3.png'] },
  { id: 'gran-teatro', nombre: 'Gran Teatro Municipal', cliente: 'Municipalidad de Lima', tipo: 'Institucional', ubicacion: 'Cercado de Lima', anio: 2021, desc: 'Participación en la ingeniería de uno de los espacios culturales más emblemáticos del país.', fotos: ['images/recurso-3.png', 'images/recurso-2.png'] },
  { id: 'hotel-andiamo', nombre: 'Hotel Andiamo', cliente: 'Andiamo', tipo: 'Hoteles', ubicacion: 'Miraflores', anio: 2021, desc: 'Ingeniería de instalaciones para hotel urbano.', fotos: ['images/recurso-4.png', 'images/recurso-1.png'] },
  { id: 'tren-electrico', nombre: 'Línea 1 y 2 del Tren Eléctrico', cliente: '—', tipo: 'Infraestructura y Transporte', ubicacion: 'Lima', anio: 2020, desc: 'Ingeniería para uno de los proyectos de infraestructura de transporte más importantes del Perú.', fotos: ['images/recurso-5.jpg', 'images/recurso-3.png'] },
  { id: 'clinica-san-borja', nombre: 'Clínica San Borja', cliente: '—', tipo: 'Educación y Salud', ubicacion: 'San Borja', anio: 2020, desc: 'Ingeniería eléctrica, mecánica y sanitaria, incluyendo gases medicinales.', fotos: ['images/recurso-bim-monitor.png', 'images/recurso-1.png'] },
  { id: 'condominio-cuattro', nombre: 'Condominio Cuattro', cliente: 'Grupo Líder', tipo: 'Vivienda Multifamiliar', ubicacion: 'Comas', anio: 2020, desc: 'Diseño BIM colaborativo: eléctricas, sanitarias, mecánicas (CFD) y contra incendio.', fotos: ['images/recurso-1.png', 'images/recurso-3.png', 'images/recurso-bim-monitor.png'] },
  { id: 'qanai', nombre: 'Multifamiliar Qanai', cliente: 'Grupo LAR', tipo: 'Vivienda Multifamiliar', ubicacion: 'La Victoria', anio: 2019, desc: 'Ingeniería eléctrica para 8 torres y 1.100 viviendas.', fotos: ['images/recurso-2.png', 'images/recurso-4.png'] },
  { id: 'casa-playa-asia', nombre: 'Casa de Playa Asia', cliente: '—', tipo: 'Vivienda Unifamiliar', ubicacion: 'Asia', anio: 2019, desc: 'Desarrollo de ingeniería eléctrica, mecánica y estructuras.', fotos: ['images/recurso-1.png', 'images/recurso-5.jpg'] },
  { id: 'colegio-madrid', nombre: 'Colegio Madrid', cliente: 'Madrid Inmobiliaria', tipo: 'Educación y Salud', ubicacion: 'Surco', anio: 2019, desc: 'Ingeniería eléctrica y sanitaria para institución educativa.', fotos: ['images/recurso-2.png', 'images/recurso-3.png'] },
  { id: 'almacen-callao', nombre: 'Almacén Logístico Callao', cliente: '—', tipo: 'Industria y Almacenes', ubicacion: 'Callao', anio: 2019, desc: 'Desarrollo de estructuras, instalaciones eléctricas, mecánicas y sanitarias.', fotos: ['images/recurso-3.png', 'images/recurso-4.png'] },
  { id: 'hotel-marriott', nombre: 'Hotel Marriott Tarapoto', cliente: '—', tipo: 'Hoteles', ubicacion: 'Tarapoto', anio: 2018, desc: 'Estructuras e instalaciones eléctricas, mecánicas, sanitarias y contra incendio.', fotos: ['images/recurso-4.png', 'images/recurso-2.png'] },
  { id: 'centro-convenciones-pucp', nombre: 'Centro de Convenciones PUCP', cliente: 'PUCP', tipo: 'Institucional', ubicacion: 'San Isidro', anio: 2018, desc: 'Evaluación de instalaciones eléctricas, mecánicas y sanitarias para certificación LEED Platinum.', fotos: ['images/recurso-3.png', 'images/recurso-bim-monitor.png'] },
  { id: 'club-condores', nombre: 'Club Recreacional Los Cóndores', cliente: '—', tipo: 'Clubes y Recreación', ubicacion: 'La Molina', anio: 2018, desc: 'Desarrollo de ingeniería sanitaria y de estructuras.', fotos: ['images/recurso-4.png', 'images/recurso-1.png'] }
];
